#!/usr/bin/env bash

session=$(find ~ ~/personal ~/work ~/personal/coding ~/personal/AJATT -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr ":,. " "____")

if [[ -z $TMUX ]]; then
    tmux new-session -s "$session_name" -c "$session" || tmux attach-session -t "$session_name"
else
    if ! tmux has-session -t "$session_name" 2> /dev/null; then
        tmux new-session -s "$session_name" -c "$session" -d
    fi
    tmux switch-client -t "$session_name"
fi
