[window]
opacity = 0.95
padding.y = 2
padding.x = 1


[font]
size = 11.0

  [font.normal]
  family = "UbuntuMono Nerd Font"
  style = "Regular"


[colors]
  primary.background = "0x1c1c28"
  primary.foreground = "0xc8c8fa"

  normal.black   = "0x181a29"
  normal.red     = "0xF07178"
  normal.green   = "0xcdea9f"
  normal.yellow  = "0xffd47e"
  normal.blue    = "0x9cabff"
  normal.magenta = "0xd3a7ee"
  normal.cyan    = "0x98e4ff"
  normal.white   = "0xbfd5de"

  bright.black   = "0x282a40"
  bright.red     = "0xeb7f84"
  bright.green   = "0xe0ffad"
  bright.yellow  = "0xffee7e"
  bright.blue    = "0xbcbcff"
  bright.magenta = "0xe6c6ff"
  bright.cyan    = "0x98fffd"
  bright.white   = "0xd1e5ed"
